### ISSUE TITLE
UnboundLocalError: cannot access local variable 'daily' where it is not associated with a value

### ISSUE THREAD

**Issue by kamkuakuay** [GravelFire/MajorBot#13]
![image](https://github.com/user-attachments/assets/5990bccf-2d95-485d-a796-0890fdbc07ea)

**Comment by unkby** [comment]
+1 
такая же проблема

```
2024-08-29 07:32:11 | INFO | xxxxx | Daily Streak : 8
Traceback (most recent call last):
  File "C:\ferm\test\MajorBot\main.py", line 13, in <module>
    asyncio.run(main())
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\ferm\test\MajorBot\main.py", line 8, in main
    await process()
  File "C:\ferm\test\MajorBot\bot\utils\launcher.py", line 102, in process
    await run_tasks(tg_clients=tg_clients)
  File "C:\ferm\test\MajorBot\bot\utils\launcher.py", line 123, in run_tasks
    await asyncio.gather(*tasks)
  File "C:\ferm\test\MajorBot\bot\core\tapper.py", line 318, in run_tapper
    await Tapper(tg_client=tg_client, proxy=proxy).run()
  File "C:\ferm\test\MajorBot\bot\core\tapper.py", line 302, in run
    logger.info(f"{self.session_name} | Task : <y>{daily.get('title')}</y> | Reward : <y>{daily.get('award')}</y>")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'daily' where it is not associated with a value
Restarting the program in 10 seconds...
```
